### ISSUE TITLE
Feature Request: Disconnect via command line

### ISSUE THREAD

**Issue by FooDeas** [OpenVPN/openvpn-gui#104]
Hi dev-team!

I'm playing around with OpenVPN 2.4_rc1 on Windows and with the feature of connecting to servers without having admin permissions. It works great and I wanted to use that in my scripts.

The command `openvpn-gui.exe --connect <configfile>.ovpn` works fine but I can't find a scriptable method to **disconnect** (optional: and exit gui) from the server.

Is there any recommended/implemented way how to do that?
If not, please interpret this issue as feature request.

**Comment by selvanair** [comment]
Currently there is no way to send a message to the GUI from a script to disconnect a tunnel. The --connect xxx option was originally meant to have a shortcut to start the GUI + a tunnel, and then interactively control it. Note that you cannot send a "connect" message to an already running GUI. But what you suggest is a useful feature --- 2.4.0 is due soon so this will have to wait for a future release.

That said, the way you use it, the GUI is controlling just one connection, so you can just stop the GUI. Ideally you should send WM_CLOSE to the GUI process so that it can cleanly shutdown openvpn and exit, but that may not work right now because we pop up a confirmation dialog when GUI is stopped with open connections.

A fully scripted approach to starting and stopping openvpn without admin rights without using the GUI is possible. Use a named pipe to connect to the interactive service and send it the openvpn command line. You will get back the pid of openvpn from the service which could be used to send ctrl-C/ctrl-break to stop the process. Or connect to the management interface and send signals which is more versatile. It takes some work to implement a script like that though.

**Comment by FooDeas** [comment]
Because OpenVPN GUI asks for the passphrase, shows status and finally integrates in Windows like it should have always been.
The GUI is so much improved now and this would be a logical carry on to the `--connect` switch.

Sending a WM_CLOSE to the GUI process had no effect.

**Comment by selvanair** [comment]
@FooDeas : If interaction with the user is ok, then sending WM_CLOSE to the GUI is an option. Not sure why it didn't work for you. Note that calling CloseMainWindow() on the process is unlikely to work. You have to do the equivalent of 
h = FindWindow("OpenVPN-GUI")
SendMessage(h, WM_CLOSE, 0, 0)
Exactly how to do that would depend on the scripting environment used.

**Comment by mattock** [comment]
@selvanair : what Powershell code did you use?

**Comment by selvanair** [comment]
@mattock: I had originally tested this using FindWindow to get the GUI window handle followed by SendMessage to send it WM_CLOSE. However, SendMessage will not return until the message is handled by the GUI so PostMessage may be better. The GUI will popup a confirmation message if any connections are active so PostMessage which returns immediately will allow one to respond to the popup from the script as well.

Here is a solution along those lines:

# First signatures of the functions in user32 dll that we may want to use
 
$sig = @"
        [DllImport(`"user32.dll`")]
           public static extern IntPtr FindWindow(string className, IntPtr useZero);
        [DllImport(`"user32.dll`")]
           public static extern int SendMessage(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam);
        [DllImport(`"user32.dll`")]
           public static extern void keybd_event(Byte bVk, Byte bScan, UInt32 dwFlags, UInt32 dwExtraInfo);
        [DllImport(`"user32.dll`")]
           public static extern int PostMessage(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam);
"@

# Use the "Add-Type" cmdlet to add these methods to the powershell session -- all added to
# a class named $win32_methods

$win32_methods = Add-Type -MemberDefinition $sig -Name "Win32FindWindow" -Namespace Win32Functions -PassThru

# get the GUI window handle
$h = $win32_methods::FindWindow("OpenVPN-GUI", 0)

# Send WM_CLOSE = 0x10 to cleanly stop the GUI 
$win32_methods::PostMessage($h, 0x10, 0, 0)

# At this point the GUI  should exit if no connections are active.

# The rest is for sending the enter key to the confirmation window that pops up otherwise.
# This is very basic and no checks on whether the GUI exited or is waiting for
# confirmation is done..

sleep 1

# simulate enter key down VK_ENTER = 0xD, scan code = 0x9c
$win32_methods::keybd_event(0xD, 0x9c, 0, 0)
# simulate enter key up change the flags to KEYEVENTF_KEYUP = 0x2
$win32_methods::keybd_event(0xD, 0x9c, 0x2, 0)

**Comment by mattock** [comment]
@selvanair : regarding the [synthesized enter key press](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646304%28v=vs.85%29.aspx): can it go to the wrong windows/desktop and cause side-effects, if the confirmation dialog does not pop up?

**Comment by FooDeas** [comment]
@mattock: Yes, it will cause "side effects" if there is no connection atm.
But It's a nice workaround for scripting!

I'd be happy to see that as a clean working feature (command line switches for disconnect and/or exit) in a later release.

**Comment by selvanair** [comment]
The key press will go to the window in foreground which not without side effects. The script is very basic --- at least it needs error checking like $h is non zero before sending PostMessage etc.. If the script is running from a cmd window a simulated "ENTER" may be tolerable, but one could add  a test that the GUI hasn't exited after some delay after the PostMessage and only then send the key press. E.g,, call FindWindow again and see it returns 0 which means GUI is not running.

I'm open to adding some options to the GUI to close connections by name (like the --disconnect option that @FooDeas has been asking for) but a GUI being what it is, scripting it is not going to be perfect and will always involve some hackery.

Here are some hacks to start and stop individual connections when the GUI is alreadyrunning:

After getting the handle to the GUI main window using
`$h=FindWindow("OpenVPN-GUI", 0)`

to start the first config do
`PostMessage($h, 0x0111, 300, 0)`
change 300 to 300 +i  for the i-th connection (i = 0 to 49). Here 0x0111 stands fro WM_COMMAND and 300 is internal to the gui.

To disconnect the first config (assuming its not disconnected) do
`PostMessage($h, 0x0111, 350, 0)`

350 -> 351 for the second connection etc..

Some caveats: The GUI doesn't check the sanity of parameters in messages so the behaviour when called with a wrong/non-existent connection number (say 302 when there are only 2 connections) is undefined. 

Sending disconnect message to a non-existent connection should be safe (will be just ignored) but connect may cause an empty status window to popup or do worse things :) Sending connect when already connected is safe except that the status window will come to foreground. But these things can change in future versions.

**Comment by selvanair** [comment]
@FooDeas 
> I'd be happy to see that as a clean working feature (command line switches for disconnect and/or exit) in a later release.

Why I'm not particularly keen on features like these is because these are not normal command line options but options to send a message to running openvpn. And in case of exit it'll still cause the confirmation message to popup which requires user interaction. If such user interaction is ok, then why cant the user just press exit in the first place? 

I do understand there could be some use, but if the idea is to support scripting in a robust way, it gets fairly complicated. Anyway the GUI is not the right tool for scripted control of openvpn. However some such features are useful for automatic testing of the GUI so let's see.

**Comment by neatville** [comment]
So, I take it that it would still be pretty hacky to stop OpenVPN through a command on Windows? It looks like the latest version came around the 27th. I can currently do this to connect, and I'd hope to be able to disconnect this easily:  
`C:\Program Files\OpenVPN\bin>openvpn-gui --connect "US Chicago.ovpn" `

**Comment by selvanair** [comment]
PostMessage($h, WM_COMMAND, 300, 0) is not that hacky :) Let's see what we can come up with to support "--disconnect config_name". No promises but I'm interested in implementing a few such options that could be used to send commands to a running instance of the GUI.

**Comment by neatville** [comment]
@selvanair I tried your PS script, it asks for a confirmation to exit OpenVPN. [Someone](https://www.reddit.com/r/VPN/comments/5ozunt/how_would_you_disconnect_from_openvpn_through_the/) recently recommended I do this, which is only one line: 
`taskkill.exe /F /IM openvpn.exe`  
That asks you to click OK after telling you the connection was closed, but unlike your script it doesn't ask if it's OK to close the connection first.

**Comment by selvanair** [comment]
If taskkill is ok with you use it -- it will kill openvpn without doing exit-notify, removing the ip on tun or any cleanup.

**Comment by war59312** [comment]
Related.. Like to see a reconnect command line option as well.

Basically, do the same thing as clicking the Reconnect button does.

**Comment by larsen0815** [comment]
+1

**Comment by cron410** [comment]
+1

This feature would be very useful for network profile switching applications like NetSetMan or when scripting folder syncs with goodsync or with torrent clients etc. etc. etc. Would be very useful to script a command to the OpenVPN GUI to connect with a specific config when my network profile switcher autoswitches to a specific profile.

**Comment by selvanair** [comment]
A test version that implements this is [here](https://github.com/selvanair/openvpn-gui/releases).

**Comment by cron410** [comment]
@selvanair your documentation for --silent_connection is wrong. You have a Hyphen where it should be an Underscore, and it doesn't actually work with the Underscore. The disconnect-all command fails silently. A specified disconnect command works great so this is a good temporary fix. I'll try to make some pull requests but this is a rather complex project and I am not a developer.

**Comment by selvanair** [comment]
Thanks for testing it. Some of these issues has been pointed out at https://github.com/selvanair/openvpn-gui/issues/5 -- I haven't yet got time to push a fixed version. Will clean it up and make a PR.

**Comment by selvanair** [comment]
Feature implemented (PR #188 ).
