### ISSUE TITLE
Give option to save "saved password" in file

### ISSUE THREAD

**Issue by jaw** [OpenVPN/openvpn-gui#220]
Windows 10 now has support for encrypting folders connected to the login password.

It would be nice if you could give option to save password to ones' AppData folder, or in the OpenVPN config directory in the home directory. Thus, it can be encrypted by the user.

Correct me if I'm wrong, but the current predictive scrambling is trivial to decrypt if someone can get physical access to the hard disk.

**Comment by selvanair** [comment]
Don't know what "predictive scrambling" means. The password is currently encrypted using Windows DPAPI, the same as what Windows uses to wrap saved credentials. For details see:
https://msdn.microsoft.com/en-us/library/ms995355.aspx

What I would like to do is to save the encrypted blob in the credentials store instead of in a custom registry value. That would make it easier for the user to manage them -- list, delete etc using the credentials manager. Would that be useful?

**Comment by jaw** [comment]
I took a quick glance in the code and it seemed like it was just using a seed from the config file's name to encrypt it... But sounds like it's secure enough for my needs as-is then.

Wouldn't hurt to have it in the credentials manager though, but no rush then.

**Comment by selvanair** [comment]
Oh, that bit called "entropy" saved in the config registry? Windows DPAPI docs use the word wrongly and its actually an extra application specific key which, in my view, adds no additional security except, probably, for proprietary software (think of hiding a key in the executable). Anyway in the GUI's implementation of save-passwords its just a harmless left-over.
