### ISSUE TITLE
Improve the Settings -> About tab

### ISSUE THREAD

**Issue by leafcutterant** [OpenVPN/openvpn-gui#238]
The information on that tab is outdated.

Also, it would be useful to display the OpenVPN version there. It can't be checked from anywhere inside thew GUI.

**Comment by selvanair** [comment]
Which version of the GUI are you running?

The about tab has the full GUI version starting 2.4.0 release. The text starts with
"OpenVPN GUI v11.x.0.0 - A Windows GUI for OpenVPN"

Starting 2.4.5 release the version of the GUI and OpenVPN are also shown on the status Window like this:  "OpenVPN GUI 11.10.0.0/2.4.5"

**Comment by leafcutterant** [comment]
I'm on 11.10.0.0/2.4.5. I thought the info is outdated because the dates have not been updated since 2016. So I may be wrong.

And you are right, the status window displays it - this escaped my attention. I was looking for it in the "About" section because usually that contains this kind of info. It may still be a good idea to display it there.

**Comment by selvanair** [comment]
Dates on copyright are cosmetic but it does look nice to have the current year in the About page -- we don't want to look outdated, do we? Will update it.

The reason why OpenVPN version is not in "About" is because its currently a static text  (fixed at compile time). As the same GUI could be used with various versions of OpenVPN, the latter's version is a run-time variable. So we show it on the status page, not on the "About" page. That said, I'm not opposed to adding that info. Not a priority for me.

**Comment by selvanair** [comment]
Fixed by #536
