### ISSUE TITLE
Silent Install hangs if OpenVPN is currently connected

### ISSUE THREAD

**Issue by cjohnson-bf** [OpenVPN/openvpn-gui#263]
First off, if this isn't the appropriate place to file this issue, I apologize and would ask that you point me in the right direction. 

This issue happens for me when upgrading from 2.3.18-I602 to 2.4.6-I602 on Windows. I'm using the openvpn-install-2.4.6-I602.exe with the "/S" command line switch for silent install. If OpenVPN is currently running and connected, the install is interrupted by "There are still active connections that will be closed if you exit OpenVPN GUI. Are you sure you want to exit?".

When running updates via a scheduled task the window with the active connection warning isn't visible, so the update hangs. 

Not sure what the solution is, maybe you don't want silent install to kill the VPN connection automatically, but maybe there should be a "force" option or something to ensure that silent updates running in the background succeed without interaction? 

Please let me know if I can provide any more info, clarification, etc.

**Comment by selvanair** [comment]
There are two messages involved here: (i) from the installer itself and (ii) from the GUI. (i) should not be shown during silent install and the response defaults to YES (i.e. close the GUI). So when /S is in use the GUi should just get WM_CLOSE from installer and lead to (ii). The GUI then pops up the message you quoted.

If running as a scheduled task, the installer may not detect a running GUI and even if it does GUI as may not get the WM_CLOSE message. NSIS uses FindWindow() to locate a running task SendMessage to send WM_CLOSE. I guess that cannot work from a scheduled task as it runs in a different session (and desktop). The same problem may arise if the GUI is running as another user who has switched out. Not sure why the installer hangs in this case instead of erroring out while copying the GUI executable.

One option is to have the scheduled task add the update job to  HKCU\Software\......\RunOnce to trigger it on next login. That will run as a user from her current desktop and should prompt to close the GUI if running etc..

An MSI installer may handle this much better... supposedly one is in the works..
