### ISSUE TITLE
openvpn-gui no longer follows disconnect_on_suspend ?

### ISSUE THREAD

**Issue by xrysf03** [OpenVPN/openvpn-gui#277]
Hello guys, thumbs up for OpenVPN and the OpenVPN GUI in Windows. I'm a long-time user.

For quite a few years, an OpenVPN client would disconnect on suspend (or resume from suspend).
By me, this is desired behavior: if someone should steal a notebook, he won't get into our private network just by opening the lid and getting to the desktop! When resuming from suspend, the user has to enter his credentials. After that, credentials caching keeps OpenVPN running across re-keying. (If caching is disabled, OpenVPN keeps pestering the user to log on every now and then, which is NOT desired behavior.)
Another advantage is that, as I keep traveling between our office LAN and my home, I can skip the OpenVPN logon when in the office, where I'm directy connected to the LAN. 

A few versions back, OpenVPN would start to auto-reconnect upon "resume from suspend".
This is not desired! I want the OpenVPN client to ask for a login+password!
But initially, I found the registry key called "disconnect_on_suspend", which solved the problem for me.

Now I'm installing OpenVPN 2.4.6 with OpenVPN-GUI 11.10.0.0, and "disconnect_on_suspend" seems gone completely. What do I do now?

**Comment by selvanair** [comment]
Three pieces of software have to co-operate to gracefully handle suspend  --- the tap driver always resets on suspend, OpenVPN daemon (openvpn.exe) used to abnormally terminate when that happens and the GUI had its own logic of terminating the tunnel (disconnect_on_suspend). We fixed the way openvpn.exe handles the tap adapter reset so that the tunnel reconnects automatically after a short delay which would trigger on resume. At that time power event handling (including disconnect_on_suspend) in the GUI was removed as it was no longer necessary for its original purpose and the code had some rough edges that sometimes caused undesired behaviour. 

But I agree that in some situations it may be useful to have an option to handle power and switch user events -- especially the latter.
  
As for re-prompting for password you can get that behaviour using --auth-nocache in the client config file. That said, it may be better to require Windows password to unlock the screen so that everything is protected, and the user needs to enter only one password.

**Comment by xrysf03** [comment]
Dear selvanair, thanks a lot for your detailed explanation.

Regarding --auth-nocache , that was obviously my first choice, even before disconnect_on_suspend .
The trouble is that --auth-nocache results in the OpenVPN "client" in Windows to prompt the user for login and password much too often. Not sure if this is due to some normal internal workings of the crypto session, or if it's merely a merciless indicator of fleeting connectivity outages between the two OpenVPN peers, that a mere human doesn't ever notice. If this could be turned into a feature request, I'd love to have that option back (disconnect_on_suspend).

And I heartily agree with your opinion that the Windows desktop should be properly locked in the first place, on resume from suspend. I do have that on my own PC but unfortunately I don't have that power over some other client setups around...
