### ISSUE TITLE
Allow checking if current config is connected

### ISSUE THREAD

**Issue by chaosflaws** [OpenVPN/openvpn-gui#286]
I am using a batch script that connects to a VPN configuration and performs some I/O operations on a remote server. Right now, I call `openvpn-gui --command connect TUC_OpenVPN` and let the script wait for 20 seconds to make sure a connection has been established. This, however, is a rather inefficient and fragile way to ascertain I am indeed connected to the VPN server.

Would you consider implementing something along those lines? For starters, something like `--command status <conn>` that responds with:

- 1 if still connecting
- 0 if connected successfully
- -1 if something went wrong

would be perfectly fine.

As I am writing this, it occured to me that I could just check for the last line in the log file, which probably works, but is hardly optimal.

**Comment by cron2** [comment]
Hi,

On Wed, Dec 05, 2018 at 04:36:25PM -0800, chaosflaws wrote:
> As I am writing this, it occured to me that I could just check for the last line in the log file, which probably works, but is hardly optimal.

You can just use "up $script" in the openvpn config to create a file
as a signal for "session is up!"

(Do not try to run your remote activies from "up" - this is a synchronous
call, so while the up script runs, openvpn is not active)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment]
To add to what Gert suggested, its not easy to support a --command status that gives a result back. --command is implemented using DATA_COPY messages and we do not have a way of getting a return message. All we know is whether the message was delivered or not. That's why the current "--command status name" just pops up the status window of the connection.

A smarter implementation using some other form of IPC is possible but I have no plans for it.

As for --up script, you could also run the script from the gui using <config_name>_up.bat which wont block the OpenVPN.exe process.
