### ISSUE TITLE
OpenVPN GUI doesn't show up in system tray

### ISSUE THREAD

**Issue by AkitoFire** [OpenVPN/openvpn-gui#287]
OpenVPN GUI doesn't show up in system tray.
I tried reinstalling the program, restarting, ... etc.
In Windows' event log, there comes this message:
"OpenVPN GUI
Previous instance not yet ready to accept commands. Try again later."
But there is no previous instance open.
Thank you in advance.

**Comment by selvanair** [comment]
Open task manager and make sure no other GUI process is running. That message in the event log can result if the GUI is running but did not get to the point of creating the parent Window. Apart from rare race conditions (starting two instances in rapid succession) this should not happen.

If no other GUI process is running, this could be due to an unexpected error in locking the semaphore used to detect whether we are the first instance. Unfortunately we do not check for errors and assume failure to get a lock means we are not the first instance. If the problem persists, please provide details of OS and openvpn/GUI versions.

**Comment by AkitoFire** [comment]
Firstly, thank you for your comment!
And secondly, I got the solution: I removed some entries in regedit that didn't automatically get removed when I uninstalled OpenVPN GUI. Now, I reinstalled the program and everything works fine again.

**Comment by selvanair** [comment]
Could you tell us what those offending registry entries were? We do not want the process to hang or wrongly detect a running instance because of registry entries -- may be there is a subtle bug that needs fixing.
