### ISSUE TITLE
Options error: --pull-filter cannot be used with --mode server

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-gui#293]
https://community.openvpn.net/openvpn/ticket/1164#ticket

https://github.com/OpenVPN/openvpn-gui/commit/4cb55f1e5862086df05dac8f868b90f1241229ea

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/openvpn/commit/bb1ea491cd16d11b448342e8287beacae619f980

**Comment by ronewxp** [comment]
pull-filter ignored for --mode server

**Comment by cron2** [comment]
hi,

On Wed, Apr 21, 2021 at 01:22:32AM -0700, MD SAKIL MAHMUD wrote:
> pull-filter ignored for --mode server

--mode server does not pull, so pull-filter does not make sense - and
that's what it is telling you.  

This is a client-side option, not server-side.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
Hi,

On Wed, Apr 21, 2021 at 01:22:32AM -0700, MD SAKIL MAHMUD wrote:
> pull-filter ignored for --mode server

Oh, I looked into my crystal ball, and it says "you are trying to
run an OpenVPN server on Windows, started from the Windows GUI".

Right?

In that case, I remember that we had this issue before (because the GUI
injects pull-filter commands into the openvpn command line) but it got
solved somehow.  Please do some googling.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by Meserias** [comment]
Dear Gert, 
you will need to fix your crystal ball because it's not helping too much, our community, didn't he ? 
Anyway, after upgrade to 2.5.4 from 2.5.3 my i got the same error.

The easiest solution is to remove read-only attribute of file openvpn-status.log which usually it located under same folder where config file (.ovpn) is. I think this should be considered a workaround but should be further investigated.

**Comment by selvanair** [comment]
Are you saying the error --pull-filter cannot be user with mode server has resurfaced in 2.5.4? Or are you reporting the read-only status-file problem in 2.5.4 discussed in #1430? A fix for the latter is in the works.

**Comment by Meserias** [comment]
> What "should be investigated" and what "is happening"? If you are referring to the error caused by files like status log created as read-only, please wait for a fixed release which will be available soon. In the mean time continue to use 2.5.3.
> 
> If its something else, please be more more precise.

what is happening > it's the fact that my workable server configuration on 2.5.3 it's not loaded anymore by new release 2.5.4
What should be investigated ? > IMHO I think it's obvious that this must be considered a showstopper since it's ruin an already workable and stable server configuration.

**Comment by cron2** [comment]
Hi,

On Sun, Oct 17, 2021 at 09:19:57AM -0700, Meserias wrote:
> > What "should be investigated" and what "is happening"? If you are referring to the error caused by files like status log created as read-only, please wait for a fixed release which will be available soon. In the mean time continue to use 2.5.3.
> > 
> > If its something else, please be more more precise.
> 
> what is happening > it's the fact that my workable server configuration on 2.5.3 it's not loaded anymore by new release 2.5.4

Unless that comes with a description of the issue, it is not happening.

Like: WHAT does not work?  Is there an error message?  Anywhere?

And why are you putting this in an unrelated ticket?

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
