### ISSUE TITLE
Can't Connect from Multiple Logins to Same Servers Using OpenVPN GUI

### ISSUE THREAD

**Issue by sworcester-hsdmetrics** [OpenVPN/openvpn-gui#309]
We have a Windows 2016 server where we have installed the OpenVPN GUI software. It appears that we mostly can't connect to the same connection from multiple logins. We have three servers that we're trying to connect to, which we have labeled TEST, APP and APP1. Somehow, one of my collegues and I are both connected to TEST right now from our respective logins on the Windows 2016 server. But we have a third colleague who cannot connect to TEST. She's connected to APP1 though, and when I try to connect to APP1, I get the attached error on the screen. I've also attached a copy of the log file.

Shouldn't each of us be able to connect to all three servers from our respective logins on the Windows 2016 server, at the same time? I ran through the process of increasing our connections from 1-6, but at the moment we only have three connections running between our three logins.

Please advise.
![Screen Shot 2019-08-16 at 10 37 15 AM](https://user-images.githubusercontent.com/22273815/63186510-973c9480-c02a-11e9-8f92-3e464e19b7b2.png)
[app1.log](https://github.com/OpenVPN/openvpn-gui/files/3510549/app1.log)

**Comment by selvanair** [comment]
If you are referring to multiple RDP sessions to the same server, when one user is connected to a VPN server you have a tunnel that is available system wide and all users should be able to use it. Not sure why you want multiple users establish independent tunnels to the same server.

OpenVPN GUI has not been written with the view of supporting multiple users running it in parallel though it may work in some situations. For example, if all users have the same set of configs and each user only connects to a different server I think it should work. The port used for the management interface is computed from an internal index number of the config and will very likely cause conflicts in other cases. That is exactly what happened when you connect to APP1 with your colleague also connected to it -- both connections tried to use the same port for management interface. The reason why you and another colleague "successfully" connected to TEST in parallel is probably because the conflict was avoided by something like TEST is, say, the second config in your profile but it is, say, the third config in your colleague's profile. Evidently not a reliable way to run the program.

In any case multiple OpenVPN processes accessing the same server is unlikely to be useful without some form of network isolation/namespaces.
