### ISSUE TITLE
OpenVPN GUI force fullscreen application to desktop even if "silent connexion" is activated

### ISSUE THREAD

**Issue by redace0001** [OpenVPN/openvpn-gui#329]
I use OpenVPN a lot to use a bunch of programs that can't access some services via my connection when I'm using some special WIFI (like in schools) that normally block almost all protocols I need.

Because the connection is sometime a bit unstable or simply because the server changes it's password or ask for a new handshake, the connection screen of openVPN Gui opens so I can "reenter" the username/password. To avoid that (because the password almost never changes on my server) i use silent connection so it connects without asking the password if it's correct.

But sometimes when I'm using fullscreen applications, a problem occurs on the connection and so the connection window is prompted again each time (if the "silent connection" mode is deactivated). The problem is that when one of this little reconnection happen when I'm in fullscreen, the connection window is not prompted but GUI still returns me to the desktop when I use silent connection. It's very annoying because a lot of fullscreen programs don't like to ALT-TAB and sometime simply crash.

**Comment by selvanair** [comment]
Even when silent-connection is on, password dialogs are created and then auto-submitted. This may be the reason for the bahaviour you see. Improving this may be useful but not a priority for me right now.

That said, look into why the GUI is being asked for password during reconnects. Unless 2FA is in use (not your case), the core can cache the password and not prompt the GUI during reneg or even reconnects caused by network errors. Unless you use --auth-nocache, password is cached by  the core and reused. That should almost completely eliminate the need for any password dialog in the GUI when you are not actively interacting with it.

**Comment by selvanair** [comment]
No response. Closing.
