### ISSUE TITLE
OpenVPN Gui 2.4.8 cannot read the Windows 10 Maschine Certificate Store

### ISSUE THREAD

**Issue by colorenz** [OpenVPN/openvpn-gui#336]
Hi,

the OpenVPN Gui client cannot read the Windows machine certificate store with the interactive service. 

If I start the OpenVPN Gui with admin rights this works without problems. How can I fix the error? Is this built into the interactive service? How can i debug this?

https://community.openvpn.net/openvpn/wiki/OpenVPNInteractiveService

--cryptoapicert "SUBJ:"

Best Regards

Constantin

**Comment by selvanair** [comment]
The certificate and its private key are accessed by openvpn itself which runs as the user who starts the GUI. If the private key is access restricted, then the user will not be able to sign with it. Check the access permissions on the key and grant access to 'all authenticated users' or those in a  particular group depending on your needs  (say 'OpenVPN Administrators' group if you ave one).

Alternatively load the certificate to user's store if that is appropriate.

Adding support for certificate access through the service is not ideal as that will potentially open up more access rights than required.

**Comment by colorenz** [comment]
Hello,

it is a computer certificate, which is supposed to identify the computer and its system services. If we allow any VPN user to read the certificate, it is much more insecure than if it is a system service. The old openvpn service was able to read the certificate with the OpenVPN Mi Gui, but the interactive service was not able to read it. 

Best Regards

**Comment by selvanair** [comment]
MI-GUI depends on running openvpn.exe as SYSTEM (from a  service at boot time) and only the GUI as user. Its still openvpn.exe that accesses certificates, no service is involved. And that also **requires** certificates to be in the machine store as the process is running as SYSTEM. 

OpenVPN-GUI uses the interactive service so that both the GUI and openvpn.exe can run with limited privileges providing more security. As certificates are always accessed by the openvpn.exe process, it allows users to have certificates in their own store or use those in the machine store based on permissions granted by an admin.

**Comment by colorenz** [comment]
But then I give every normal user rights to read these computer certificates and to authenticate himself in case of doubt.  This gives me a great attack vector. By malware in the normal user context and reading the certificate.

It would be good if this is implemented like with other solutions (Junos Pulse / Citrix Netscaler VPN) and a trustworthy system service  installed by an administrator(Softwaredistribution like SCCM, Martix, Intune) like the openvpn service reads the certificate.

Translated with www.DeepL.com/Translator (free version)
