### ISSUE TITLE
What plugins and IDE i need to use to edit the GUI?

### ISSUE THREAD

**Issue by rafaelsetragni** [OpenVPN/openvpn-gui#348]
Ive downloaded your code to edit the GUI and make it more friendly. I installed Visual Studio Community edition from scratch and download your repository.

But i hadnt be able to edit the GUI. All the files are showed as .cpp and .h files. The .rc file also as displayed as c++ file.

What pluggins did you used on your Visual Studio to be able to edit the layout? What Visual Studio did you used?

**Comment by rafaelsetragni** [comment]
Ive discovered whats goin on with the resource files that are not allowing to edit the layout.

The elements was copy and paste by hand, duplicating all the elements IDs and corrupting the file content. Thats why Visual Studio cannot open the dialog box for edition.

And all those translation files are also copies one from another, duplicating once more all those IDs. So all of then are corrupted too.

Isolating just the english one (/res/openvpn-gui-res.rc) i was capable to replace by hand and fix all the copy and paste corruption. So now the files are available for direct layout edition on VS2019, as you can se on the prints.

![openvpn-gui for edition](https://user-images.githubusercontent.com/40064496/82070597-58b43300-96ab-11ea-8338-9e0f5cd52c4f.png)

BUT, i believe the way to translate the files was not the best one to do. So i will figure out how to make it happen by the right way.

**Comment by selvanair** [comment]
Building on Windows using VS is not officially supported. I think @lev had copied some minimal stuff to use VS for testing but its not used in production. Use mingw on Linux or Windows -- also see BUILD.rst.

**Comment by mattock** [comment]
Years ago I translated lots of software, including openvpn-gui, so I have to agree with @rafaelsetragni. Looking from the translator's perspective it would be optimal to have the strings in a file which computer-aided translation files can read directly. Examples are [GNU Gettext po](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) and Java properties files. When I was actively translating I used [OmegaT](https://omegat.org/). Not sure if that is still the best open source software translation tool, but it [seems](https://github.com/omegat-org/omegat) to be actively maintained.

In any case, they all work by creating a "translation memory database" which contains the translated strings. So, they do _not_ touch the original source files. Instead, they load the source file, get the translations for the strings from the database and allow you to export a translated file. This enables much easier maintenance of the translation, e.g. no need to figure out by yourself which strings have been added to the application since you translated it the last time: you just feed it the updated source file. Also, if some of the original strings have changed, you get a percentage match (e.g. 90% the same as original) along with the option to use, or change, your old translation for that particular string.

So, if translations could be moved to a easily machine-readable file (e.g. one supported by [OmegaT](https://omegat.org/)) that would be great.

**Comment by lstipakov** [comment]
> Building on Windows using VS is not officially supported. I think @lev had copied some minimal stuff to use VS for testing but its not used in production. Use mingw on Linux or Windows -- also see BUILD.rst.

Looks like tagging went a bit wrong :) But yes, there is a basic VS support but you cannot really edit resources there. I remember there was some issue with MS resource compiler which didn't exist with mingw resource compiler, which was the biggest obstacle why I didn't port resources to VS.
