### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn-gui#373]
This is my first time poking around in an open source project, so forgive my ignorance, if this is a simple matter, that I am facing.
I have some errors when I try to build the project, right after cloning. 14 ones, exactly like this one, but with different external symbols.

Error	LNK2019	unresolved external symbol d2i_PKCS12_fp referenced in function ChangePasswordPKCS12	openvpn-gui	\Documents\openvpn-gui\passphrase.obj

I am not sure what this problem is reffering to, or if this is some kind of dependency related problem.
Any ideas would be deeply appreciated, also let me know if I should present some additional info/data about this matter.
![errors](https://user-images.githubusercontent.com/42838737/97193020-d2972f00-17a8-11eb-9abd-405f93a8955f.jpg)

**Comment by selvanair** [comment]
I do not build using MSVC, but the errors point to missing OpenSSL headers. The only feature that is dependent on OpenSSL is the menu option to change the private-key password which can be disabled by a preprocessor define of DISABLE_CHANGE_PASSWORD. Then the GUI can be built without OpenSSL. Otherwise you will need to install OpenSSL headers and libraries.
