### ISSUE TITLE
OpenVPN GUI does not recognize commands as parameter of up

### ISSUE THREAD

**Issue by chaosflaws** [OpenVPN/openvpn-gui#403]
When adding the `up` parameter, I can specify a script to be executed (`up my-test-script.bat`), but adding a shell command does not seem to work:

`up "net use S: \\\\server\\share"` leads to `Options error: --up script fails with 'net use S: \\server\share': Unknown error (errno=123)`.

`up "net use"` leads to `Options error: --up script fails with 'net': No such file or directory (errno=2)`

The default value for `script-security` is 1, which allows the execution of some built-in commands, so that should not be the issue.

The obvious workaround would be to put the shell command into a script, but I would like to avoid lowering my security settings (the `--script-security level`). Is this a bug or am I missing something?

**Comment by TinCanTech** [comment]
When `openvpn` launches a script (eg: `--up`) there is no `$PATH` env-var and so cannot find `net`.

Try specifying `net` as `\Windows\System32\net` (Or where-ever it lives).

**Comment by selvanair** [comment]
To add to that:
(i) "Scripts" are not run under a command shell. But executed as is without prepending any PATH to it, so the file name should be either absolute or relative to the working directory (the same as where the config file is). The option parser checks for the existence of this file which means the file extension should also be provided and that's the error you are seeing.

(ii) Scripts like `--up  up_script.bat`  are called with a number of additional arguments generated internally and may cause commands like net.exe to fail. Using a wrapper script instead of directly calling the executable is not only more convenient and less error-prone, but unavoidable in most cases. Also you will need --script-security 2 in either case.
