### ISSUE TITLE
disallow empty passwords ?

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-gui#417]
we observe the following pattern in user behaviour: when they setup new PC, sometimes they *forgot* to press TAB to switch to "password" prompt and type password right after the login, i.e. user<missing tab>password. 

thus, password itself is empty, and sent as empty.

I'm not sure whether empty password is legitimate, maybe we should change OpenVPN-GUI behaviour to disallow empty passwords ?

I'd suggest to make "password" field red if OK is pressed on empty password. Thus we even do not have to translate it.

@selvanair , what do you think ?

**Comment by chipitsine** [comment]
I cannot upload screenshot. Something changed in github upload :(

**Comment by selvanair** [comment]
In OpenVPN core, empty username is not allowed, but empty password is not an error. I guess passing only username has its use cases like SSO where the auth process is federated out, or done out of band by other means. In such cases one may not want to send the password to the server.  

Ideally, we should have a way of indicating in the prompt process what inputs are required so that the rest can be greyed out in the dialog. Then it would be appropriate to demand a non-empty entries for all enabled inputs including password. In v2.6, we have some newer methods to support out of band authentication, but I don't think the initial username/password prompting has been improved. 

We could stop making OK the default button as soon the username is filled-in so that hitting return would not submit the dialog if password is empty. Without disabling OK so that it could be clicked with empty password.

**Comment by chipitsine** [comment]
may I suggest the following approach ?

1) default behaviour is changed, i.e. empty passwords are disallowed
2) OK button is not disabled (people even do not press it, but hit Enter instead), 
3) if user hit Enter, password field becomes red on background, dialog is still there, connection is not started
4) if empty password is supposed to be legitimate for some reason, it might be allowed, for example, in config file


or ....

we can keep current default behaviour, but introduce additional flag in config, if it is set, empty passwords become disallowed

**Comment by TinCanTech** [comment]
Could the GUI present a user dialogue window asking for empty password confirmation ?

**Comment by selvanair** [comment]
Let's not make it more user-unfriendly. Those who mistakenly submit empty passwords is no different from those who mistype passwords. 

At best, we can make none of the buttons the defualt when all fields are not filled in though.  That should take care of those hit enter without filling in the password and still allow to press either button. Its either that or leave everything s is.

**Comment by TinCanTech** [comment]
Make the user select a button and not have `OK/Enter` selected by default. I see the logic now.

**Comment by chipitsine** [comment]
disabling buttons and outlining mandatory fields as red would be nice

**Comment by cron2** [comment]
Hi,

On Wed, Apr 21, 2021 at 10:11:23PM -0700, Ilya Shipitsin wrote:
> disabling buttons and outlining mandatory fields as red would be nice

I think pressing enter *in the password field* should still serve as
"OK!".  Otherwise it would annoy me (have to move my hands an extra
time to the mouse).

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by chipitsine** [comment]
Maybe Enter should change focus to password field if password is empty and OK otherwise?

**Comment by chipitsine** [comment]
just to mention, this is actually pretty rare situation.
usually, both fields are filled, password is saved and login happens automatically (without even pressing Enter)

only when moving to new PC, user fills empty fields for the first time. and sometimes he did not press Tab button to switch fields

**Comment by cron2** [comment]
hi,

On Wed, Apr 21, 2021 at 11:43:51PM -0700, Ilya Shipitsin wrote:
> just to mention, this is actually pretty rare situation.
> usually, both fields are filled, password is saved and login happens automatically (without even pressing Enter)
> 
> only when moving to new PC, user fills empty fields for the first time. and sometimes he did not press Tab button to switch fields

We always have to fill password field, because it's used for 2FA challenge.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by chipitsine** [comment]
I wonder whether "empty" password happens in case of 2FA. From my observation it should happen more often than I see for static passwords

**Comment by cron2** [comment]
Hi,

On Thu, Apr 22, 2021 at 02:57:31AM -0700, Ilya Shipitsin wrote:
> I wonder whether "empty" password happens in case of 2FA. From my observation it should happen more often than I see for static passwords

Never seen that.  But as long as I can press <return> in the password
field (after having entered something) I'm fine with the suggested change.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
Turns out that there is no good way to do this while still allowing empty passwords.  Having no default button doesn't seem to play very well in Windows dialogs.

I would have liked to keep allowing empty passwords -- it has its use cases and is supported by the core -- but may be the right way to do that would be have an explicit way for prompting only username.

So our options are (i) enable the OK button only if password is non-empty or (ii) leave this as is. (i) would be a regression but probably no one cares.

In all cases, enter will submit once the OK button is enabled as it's the default button.

**Comment by chipitsine** [comment]
Is empty password a common case? We may introduce some setting for that

**Comment by TinCanTech** [comment]
Just a punt for an option, how about an empty checkbox:
`[ ] Allow empty password.`
And `OK` as default button on press Enter.

If the password and checkbox are both empty then throw an error.
If the password is filled in then the checkbox would not be required to continue.

**Comment by chipitsine** [comment]
yeah, either checkbox or config setting (so, config would be delivered right with empty passwords)

**Comment by selvanair** [comment]
I decided to go with @chipitsine 's original suggestion -- i.e., require non-empty password (PR #419).

If the administrator doesn't want the user to submit a password, one should not prompt for it. So instead of making it even more difficult for the user having to ignore an input and also click additional check boxes, let's just say password input is required if prompted for. 

The "submit only username" can be handled when OpenVPN grows proper support for indicating it.

**Comment by ilkondr** [comment]
You've just made it absolutely impossible to connect using perfectly correct config (with empty password), because some people _forget_ to press TAB. Did I get it right?
Are you crazy guys?

**Comment by cron2** [comment]
Why is your config asking for a password if "empty" is a valid answer?  Just leave auth {{{--auth-user-pass}}} from the config and be happy everafter.

**Comment by ilkondr** [comment]
I think it is still asking for username as far as I understand.
My server is Mikrotik device and I can't connect with no auth-user-pass option.

**Comment by selvanair** [comment]
I was reluctant to not allow empty password, and was a compromise. Given that openvpn.exe expects a non-empty username, but accepts empty password, this was not a smart change.

**Comment by schwabe** [comment]
If a configuration requires an empty password you should not use `auth-user-pass` in the config. And if the UI is still asking for a password that is a bug. If the command line openvpn allows an empty password we might want to adjust that to also require a password.

**Comment by selvanair** [comment]
Empty password currently serves as a way of providing a username even when password is not in use or when password has to be submitted by othe rmeans. Eg., when the actual authentication is federated out, submitting just the username is a useful feature. In such case one doesn't want to expose the password to the server. There could be other uses of username-only. 

So, unless we add a new option like auth-username, supporting empty password is a useful thing.

Not saying that showing a dialog with two fields when only one is required is good UX.

**Comment by darkbasic** [comment]
A security researcher friend of mine asked me how this issue is supposed to be linked to my CVE so I would like to point out to anybody else who stumbles upon this that they linked the wrong issues in the [v2.6.7](https://github.com/OpenVPN/openvpn/releases/tag/v2.6.7) release notes. The correct links were supposed to be the following (same numbers but different repository/type):
https://github.com/OpenVPN/openvpn/issues/400
https://github.com/OpenVPN/openvpn/issues/417
