### ISSUE TITLE
WARNING: No server certificate verification method has been enabled. 

### ISSUE THREAD

**Issue by robotcll** [OpenVPN/openvpn-gui#453]
Mon Sep 13 09:10:53 2021 OpenVPN 2.4.8 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Oct 31 2019
Mon Sep 13 09:10:53 2021 Windows version 6.2 (Windows 8 or greater) 64bit
Mon Sep 13 09:10:53 2021 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10

**Mon Sep 13 09:10:55 2021 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.**

Does  anybody know how to handle this warning?

**Comment by robotcll** [comment]
Or can I ingore it?

**Comment by derickza** [comment]
@selvanair please excuse my ignorance - how do you add that line to the client config - don't even know where it is or how to find it and google is not helping - all these linux solutions are so techincially vague they need solutions themselves - is there a real laymans way of doing this step by step - almost like i'm a baby 

"Add remote-cert-tls server to your client config" = do something - I need to know the how to do something.

would you be able to assist. pls pls.

**Comment by selvanair** [comment]
> @selvanair please excuse my ignorance - how do you add that line to the client config - don't even know where it is or how to find it and google is not helping - all these linux solutions are so techincially vague they need solutions themselves - is there a real laymans way of doing this step by step - almost like i'm a baby
> 
> "Add remote-cert-tls server to your client config" = do something - I need to know the how to do something.

If you do not know what that means, point your server administrator to this thread so that they can provide a fixed configuration.

**Comment by cron2** [comment]
Hi,

On Tue, Nov 22, 2022 at 10:00:17PM -0800, derickza wrote:
> I will just keep trying until I either find a complete application that works on Linux or Google myself to death looking for a set of copy and paste terminal instructions that works for me. That I don???t understand in any case.

The issue here is: to use OpenVPN, you need to have a config file with
details about servers, secret keys, etc - that can not be provided by
us in an installable package.

Either the server operator provides that config file (and then he's the
responsible person for questions about that config file), or you'll have
to learn how these pieces all work together.

There's no way to do "shrinkwrap VPN".

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
Hi,

On Tue, Nov 22, 2022 at 11:41:39PM -0800, derickza wrote:
> Thank you for your reply
> 
> Our client uses checkpoint vpn and they only give us a username a password and the gateway i.e gateway.XXX.co.za
> 
> and then we download the client - install it - enter our details and bingo! we are in.
> 
> but on Linux - checkpoint is even more difficult to understand or try to get working. so was looking for something else that I can install enter my details and connect.

I don't think that checkpoint uses the OpenVPN protocol, so using the
OpenVPN client with a checkpoint server is not going to work.

Specifically, OpenVPN needs a full config file, not just "server + 
username + password".

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by QuazyMorda** [comment]
Add to client config for certificates to work in a file

key-direction 1             # <tls-auth> section
remote-cert-tls server  # <ca, cert, key> section

**Comment by dangdkhanh** [comment]
Hi guys,
for those who simply want to change location like me and have no network knowledge.
Can you be more specific about which file to custom and where it location? Where in the file can I add your code?
because I can't find client config file but only client.opvn (C:\Program Files\OpenVPN\sample-config)
