### ISSUE TITLE
2.5.4 breaks working server configuration

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-gui#457]
> What "should be investigated" and what "is happening"? If you are referring to the error caused by files like status log created as read-only, please wait for a fixed release which will be available soon. In the mean time continue to use 2.5.3.
> 
> If its something else, please be more more precise.

what is happening > it's the fact that my workable server configuration on 2.5.3 it's not loaded anymore by new release 2.5.4
What should be investigated ? > IMHO I think it's obvious that this must be considered a showstopper since it's ruin an already workable and stable server configuration.

_Originally posted by @Meserias in https://github.com/OpenVPN/openvpn-gui/issues/293#issuecomment-945153114_

**Comment by schwabe** [comment]
@Meserias we are obviously not aware of the issue and can also not reproduce it. So *you* need to work with us to help us understand why it breaks for you, otherwise we really not help you. Also running OpenVPN server under Windows *with* OpenVPN-GUI is a very obscure corner case that not many people do. Just because something is very important to you does not mean it is a very widespread use or problem.

**Comment by selvanair** [comment]
Anyway, temporary files created for client-connect script, deferred auth etc are mistakenly generated as read-only in 2.5.4 Windows release. Using EC certificates from Windows certificate store with cryptoapicert option, and use of ECDH(E) key exchange (partially) are also broken (Trac 1430, 1433, issue #456) . All of these are likely to affect server configurations.

Wait for a fixed Windows release. If you continue to experience issues after that report back with more *details* like the error message in logs, what works, what doesn't etc. **For now use 2.5.3**.

**Comment by Meserias** [comment]
I'm confirming that initial issue that I reported a couple of days ago, it's now resolved.
