### ISSUE TITLE
Ver 2.5.4-gui on Win 10: after connection GUI dialog immediately minimizes to icon taskbar tray-connected status icon will disappear when clicked

### ISSUE THREAD

**Issue by mapper14** [OpenVPN/openvpn-gui#463]
Installed OpenVPN-2.5.4-I604-amd64.msi on Win 10 Build 19043.
I'm using config scripts supplied by a paid VPN service.
After successful connection to server, GUI dialog immediately minimizes to an OpenVPN solid shaded icon indication active connection.
Clicking on this icon to reopen GUI dialog causes icon to disappear with no GUI dialog reopening.
After icon disappears connection persists but user has lost control to disconnect or perform any action on current connection.
So far, my only solutions to closing the connection are:
1 - Kill the OpenVPN Daemon process in Win Taskmanager
2 - Reboot
Previous builds of OpenVPN I've installed and used, 2.4.0, 2.4.2, on Windows 7 and 10 did not immediately minimize, used Hide button to minimize,  and clicking the minimized icon would reopen the GUI dialog to manually disconnect.

**Comment by selvanair** [comment]
Check task manager to see whether the GUI is dead or still running.  If its running, the icon may be in the "hidden icons" list of the tray.

If GUI is really dead, check event log for any errors logged. Also post the tail end of the log file in %USERPROFILE%/OpenVPN/log/<config-name>.log -- it will show at what point the GUI (management client) disconnected.

**Comment by mapper14** [comment]
When the icon disappears, my Win 10 Taskmanager always shows the task "OpenVPN Daemon" is still running, and I'm remain connected to the VPN server and am obtaining a VPN Proxy IP that I expect - by doing a quick check on WhatsMyIP
The Icon is definitely not hidden in 'hidden task' popup in the taskbar. To make absolute certain I've set Windows Tasksettings options to display ALL minimized task, dialogs or app in my Taskbar.  It's just simply NOT there and I have no access back to the OpenVPN-gui dialog.

Here's the last log file but understand that the event at 2021-11-10 02:39:12 is a manual END of the OpenVPN Daemon.  I was still connected to that Montreal server up to that point.

[Canada-Montreal_2_TCP444_SMART.log](https://github.com/OpenVPN/openvpn-gui/files/7599955/Canada-Montreal_2_TCP444_SMART.log)

Was this fixed in #464?

**Comment by selvanair** [comment]
> Was this fixed in #464?

The issue fixed in #464 happens only when you import a connection profile (config file), usually with no other connection profiles present. If you are experiencing this every time a connection is established, its something else, unrelated to import.

The logs you posted shows that "management client" (which is the GUI) disconnected when the connection was terminated a little over 4 hours after the initial connection. That means the GUI is alive and running till the end --- its not crashing. You can verify that also by listing all running processes in task manager and looking for openvpn-gui.exe.

I do not know why the tray icon disappears. Right click on the taskbar and select `Taskbar settings` --> `Select which items appear on the taskbar` and see whether `OpenVPN GUI for Windows` is listed there. If its missing and openvpn-gui.exe is shown as running in task manager, try a clean install of 2.5.2 or 2.5.3 to see whether this is something peculiar to your system.

Release 2.5.5 which will include the fix in #464 is expected to be out soon.

**Comment by selvanair** [comment]
Closing for lack of follow-up.
