### ISSUE TITLE
OpenVPN How to get Username from Windows (mostly v10 64Bit) Registry if in case forgotten ?

### ISSUE THREAD

**Issue by vivekwebm2020** [OpenVPN/openvpn-gui#475]
Please take look at this SO (StackOverflow) [question](https://stackoverflow.com/q/70934162/365107) where I have explained the issue I am having for (decrypting if stored encrypted &) exporting the OpenVPN Username from Registry key-value.

I've also put the code I tried to fetch the Username(almost the same way as we fetch Password sucessfully), but if you don't want to take hassle of copying the code from there, then here it is (hope you(or anyone in your team) know Powershell):
```ps1
Add-Type -AssemblyName System.Core
Add-Type -AssemblyName System.Security
$keys = Get-ChildItem "HKCU:\Software\OpenVPN-GUI\configs"
$items = $keys | ForEach-Object {Get-ItemProperty $_.PsPath}

foreach ($item in $items)
{
  $entropy=$item.'entropy'
  $username=$item.'username'
  $encryptedbytes=$item.'auth-data'
  $entropy=$entropy[0..(($entropy.Length)-2)]
  $username=$username[0..(($username.Length)-2)]

  $decryptedbytes = [System.Security.Cryptography.ProtectedData]::Unprotect(
    $encryptedBytes,
    $username,
    [System.Security.Cryptography.DataProtectionScope]::CurrentUser)

  Write-Host ([System.Text.Encoding]::Unicode.GetString($decryptedbytes))
}
```
Where am I wrong in the code ? How to fix it and get the intended Username ?

**Comment by selvanair** [comment]
> Where am I wrong in the code ? How to fix it and get the intended Username ?

A number of things:
(i) Username is not encrypted. Though stored as REG_BINARY its a null terminated unicode string. You can extract it as
   $username = [System.Text.Encoding]::Unicode.GetString($item.'username') 
   # trim the null
   $username = $username.Trim([char]0) 

Note: This may change in future -- there has been some requests to keep the username also encrypted. If/when that happens you will have to check the version in the registry (HKCU:\Software\OpenVPN-GUI\version) to determine the format.

(ii) In case you want to extract the encrypted bytes, the call to Unprotect would be Unprotect($encryptedBytes, $entropy, 'CurrentUser') -- your code snippet has $username instead of $entropy as the second argument. That would give a byte array which could be decoded as Unicode.
But,again, no call to Unprotect() is required to extract the username.

**Comment by vivekwebm2020** [comment]
Thanks @selvanair
