### ISSUE TITLE
OpenVPN CreateProcess Failed

### ISSUE THREAD

**Issue by SunnyWjw** [OpenVPN/openvpn-gui#492]
**When I installed the openvpn-gui.exe file compiled from the OpenVPN-gui source code, it prompted me to CreateProcess Failed**

![image](https://user-images.githubusercontent.com/11763317/163959564-2c17ae36-1dc5-4b21-add3-697c160162be.png)

![image](https://user-images.githubusercontent.com/11763317/163959581-ff6227c8-6c4a-41b7-b50e-f16b31f3a1ad.png)

**According to the online instructions, I need to delete the OpenVPN GUI related content in the registry, but I found that there is no relevant data in my registry**

<img width="832" alt="image" src="https://user-images.githubusercontent.com/11763317/163960069-4b112766-2259-4dbc-9011-9572a6f01d16.png">

![image](https://user-images.githubusercontent.com/11763317/163960098-e5003402-45a5-43cb-b981-d427a0802a3c.png)

![image](https://user-images.githubusercontent.com/11763317/163960109-a5c13d1b-6783-427d-af0a-aef59eaba6e3.png)

**Comment by lstipakov** [comment]
So what is the problem exactly? OpenVPN-GUI requires openvpn.exe to work, it is now very useful otherwise. The easiest way would be to just install openvpn windows client (https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.6-I601-amd64.msi) which creates all registry keys during installation.

Maybe we can help you if you tell us what do you what to achieve.

**Comment by SunnyWjw** [comment]
The problem has been solved
