### ISSUE TITLE
How to update the OpenSSL version in OpenVPN

### ISSUE THREAD

**Issue by SunnyWjw** [OpenVPN/openvpn-gui#493]
When I was compiling OpenVPN v2 5.6, it reminds me that the version of OpenVPN is too old. But I checked the version of OpenSSL I installed, which is Version 1.1.1n.
When I try to use  `./configure OPENSSL_CFLAGS=-I/cygdrive/c/Program Files/OpenSSL/include OPENSSL_LIBS="-L/cygdrive/c/Program Files/OpenSSL/lib -lssl -lcrypto -ldl"` to specify the path of OpenSSL for compilation, it prompts me that this is invalid

Now, how to modify the version of OpenSSL in OpenVPN to upgrade it to V1.1.1n ？

***********************************
Compilation environment:
Compiling software: cygwin64
OpenVPN version: v2.5.6

![image](https://user-images.githubusercontent.com/11763317/165240485-85421f95-4a49-4313-adc0-f3f882a3e63b.png)
![image](https://user-images.githubusercontent.com/11763317/165240559-1c252d5a-96cd-4b0f-b621-d55daeb14ed5.png)

**Comment by lstipakov** [comment]
Since you use Windows, I recommend to use CMake-based build system, which uses vcpkg as dependency manager. openvpn-gui will use whatever openssl version (1.1.1 or 3.0.2) installed by vcpkg.

**Comment by selvanair** [comment]
> When I try to use ./configure OPENSSL_CFLAGS=-I/cygdrive/c/Program Files/OpenSSL/include OPENSSL_LIBS="-L/cygdrive/c/Program Files/OpenSSL/lib -lssl -lcrypto -ldl" to specify the path of OpenSSL for compilation, it prompts me that this is invalid

OPENSSL_CFLAGS has spaces in the path --- it should be quoted.

As Lev said, if you can use cmake-based build it may be easier.

**Comment by dragonkyl** [comment]
OpenVPN version: v2.5.6
Openssl version: v1.1.1n

I try to use
./configure --host=arm-linux-gnueabihf --disable-lz4 --prefix=/home/ylkuai/project/openvpn-2.5.6/openvpn/a1000 CFLAGS=-fgnu89-inline LZO_LIBS=-L/opt/lib/lzo/lib LZO_CFLAGS=-I/opt/lib/lzo/include OPENSSL_CFLAGS=-I/opt/lib/openssl/include OPENSSL_LIBS=-L/opt/lib/openssl/lib LIBPAM_LIBS=-L/opt/lib/pam/lib LIBPAM_CFLAGS=-I/opt/lib/pam/include CC=/opt/a1000/toolchain/app/ext-toolchain/bin/arm-linux-gnueabihf-gcc AR=/opt/a1000/toolchain/app/ext-toolchain/bin/arm-linux-gnueabihf-ar
it's OK!


but . when i try to use
make
error has occurred
![微信图片_20220507113405](https://user-images.githubusercontent.com/41336195/167236551-b87123a6-7ac3-4f09-8d19-4f6f4ac34bac.png)

**Comment by cron2** [comment]
Hi,

On Fri, May 06, 2022 at 08:35:08PM -0700, dragonkyl wrote:
> ./configure --host=arm-linux-gnueabihf --disable-lz4 --prefix=/home/ylkuai/project/openvpn-2.5.6/openvpn/a1000 CFLAGS=-fgnu89-inline LZO_LIBS=-L/opt/lib/lzo/lib LZO_CFLAGS=-I/opt/lib/lzo/include OPENSSL_CFLAGS=-I/opt/lib/openssl/include OPENSSL_LIBS=-L/opt/lib/openssl/lib LIBPAM_LIBS=-L/opt/lib/pam/lib LIBPAM_CFLAGS=-I/opt/lib/pam/include CC=/opt/a1000/toolchain/app/ext-toolchain/bin/arm-linux-gnueabihf-gcc AR=/opt/a1000/toolchain/app/ext-toolchain/bin/arm-linux-gnueabihf-ar
> it's OK!

This looks like you are cross-building, and pointing configure to the
host libraries (intel).  OPENSSL_CFLAGS, OPENSSL_LIBS, etc. need to point
to arm-linux-gnueabihf versions of the libraries.

This is more a general "how do I cross-build things" question, and has
nothing whatsoever to do with OpenVPN *GUI* (which is windows only).  

Please don't post questions to random PRs just because the repository
has "OpenVPN" in its name.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by dragonkyl** [comment]
I'm sorry I sent it in the wrong place. And I have solved the problem.
