### ISSUE TITLE
openvpn for windows 10 app

### ISSUE THREAD

**Issue by jaiabishek** [OpenVPN/openvpn-gui#51]
do you guys have any idea in building the app for windows 10 mobiles and workstations.

**Comment by mattock** [comment]
I have not heard of any such plans. I also believe that the porting effort would be significant. As Windows phones are not really gaining momentum means that it's unlikely such an app would appear anytime soon (or ever). Regardless, I'll keep this issue open so that other people who may need "modern" OpenVPN app can chime in.

**Comment by ffes** [comment]
If somebody dares to take that path, creating a real OpenVPN provider for Win10 would be the best way.

In the action center there is a "VPN" tile. When you click that you can create a VPN connection. Then you need to select a VPN provider.

I have really not investigated but I assume MSDN has the documentation needed to create a provider. A very quick search result is https://msdn.microsoft.com/en-us/windows.networking.vpn where is stated that when you have questions about the VPN API you can contact them via e-mail.

**Comment by cron2** [comment]
Hi,

On Fri, Jul 15, 2016 at 01:01:05AM -0700, Frank Fesevur wrote:
> If somebody dares to take that path, creating a real OpenVPN provider for Win10 would be the best way.

Undoubtedly.  Unfortunately, "someone" would have to have lots of time
in his hands, or be paid for that - and I see neither right now.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by brunofin** [comment]
Hey guys,

I won't promise anything, but I'm adding this to my "to do" list when I eventually have some time to stop and research about that. It bothers me that the OpenVPN configuration is not integrated into the OS.

If I come up with something I'll send you guys a pr.

**Comment by farosch** [comment]
Any news on this? I'd really love to see this - this could also be the answer to #51, #77 and #79

**Comment by mattock** [comment]
We're eventually going to get there with the "Unified Connect" client which I believe is already in beta for the Android platform. That client will be based on [openvpn3](https://github.com/OpenVPN/openvpn3). I suspect it will take some months before anything will be available in the Microsoft Store. At the moment there are no plans to open source the Windows client.

@brunofin If you want to open source your work I suggest waiting a bit until the Windows VPN API is a bit more mature. This helps you avoid banging your head against Windows bugs. In any case I think the client using the Windows API will not be openvpn-gui, but something entirely else.

**Comment by Boca13** [comment]
Any updates on this? Having OpenVPN as a UWP VPN plugin would be great for a seamless integration with the Windows VPN functionality. Let us know if you decide to release the code and/or are open to getting some help.

**Comment by JM-Lemmi** [comment]
Just checking in on this.
Any updates?

**Comment by mattock** [comment]
@lstipakov should know.

**Comment by lstipakov** [comment]
We had a proof of concept - openvpn client using UWP VPN API, but because of:

 - we didn't manage to achieve a good performance even comparison with TAP driver (not even mentioning wintun driver, which is significantly faster)

 - Windows Phone is dead and UWP doesn't seem to get much traction

we decided to put that on the shelf.

**Comment by 123gizi** [comment]
Even with the reduced performance, I think having an UWP option would be great for Windows 10 S devices as they could still be used to connect to the home network with a lot of the routers having a OpenVPN server. This could keep the devices secure without the need to sign up for a paid VPN service and still allow access to the home NAS and even IoT devices.
Anyone needing more complex setups would still be able to use the current client...

**Comment by v1ctormoreno** [comment]
Would be great to have this option as it could enable people to log into vpn before login in their computer. Like Cisco Anyconnect.

**Comment by lstipakov** [comment]
We had prototype of OpenVPN client based on UWP, but performance-wise it was not noticeably faster comparison to tap-windows6 based client, At the moment we're focusing on the new high-performance ovpn-dco-win driver (https://github.com/openvpn/ovpn-dco-win) which provides superior performance. However, at the moment it is under development and not recommended for production use.

Note that you can use OpenVPN service for autostart feature, see https://openvpn.net/community-resources/running-openvpn-as-a-windows-service/.

**Comment by MohammedNoureldin** [comment]
Will this driver enable OpenVPN client integration in Windows seamlessly? I mean just like the other VPN protocols?

**Comment by terrorx9** [comment]
> Not at the moment.
> 
> We are now focused on getting our new driver (https://github.com/openvpn/ovpn-dco-win) into OpenVPN 2.6, which should significantly improve performance on Windows.

Would it be possible to get the windows package published via the windows 11 store at least?- that would solve my problem with having Windows 11 S Mode.

**Comment by lstipakov** [comment]
Right now it is not possible to upload openvpn-gui into the Microsoft Store. However, recently Microsoft announced plans to support "traditional" apps in store and we have been in contact with them. We'll let you know when we'll have something.

**Comment by tfonzi** [comment]
I'm working on using the [Windows VPN API](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn?view=winrt-22000) for connecting to an OpenVPN server. Seems like generally there are not a lot of resources/references available online, so any would be appreciated!

**Comment by gitnewcomer** [comment]
> I'm working on using the [Windows VPN API](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn?view=winrt-22000) for connecting to an OpenVPN server. Seems like generally there are not a lot of resources/references available online, so any would be appreciated!

Hi @tfonzi check my answer on issue #77 maybe it can help you... ;)

**Comment by salaros** [comment]
I would rather install 3-4 providers for built-in Windows 11 VPN app, than 3-4 different applications

**Comment by alex2364** [comment]
I would like to add my support for a Microsoft Store UWP app! I'm looking for a client that I can install in Windows S mode. I'm not too concerned with performance as long as it works.

**Comment by selvanair** [comment]
Closing as this as writing a UWP app for openvpn is better discussed in a new project devoted to that goal.

**Comment by TinCanTech** [comment]
Suggestion: Personally, I would not close this yet.

**Comment by gitnewcomer** [comment]
> I would like to add my support for a Microsoft Store UWP app! I'm looking for a client that I can install in Windows S mode. I'm not too concerned with performance as long as it works. Something similar to the Cisco AnyConnect app in the Microsoft Store would be great.

I still don't understand why people still like to use the limited Windows on S mode. It is so limited that we can't run any batch file or task planner. I would suggest to deactivate the S mode to be able to use windows in a more efficient way (window S mode is a false feeling of security anyway): https://support.microsoft.com/en-us/windows/switching-out-of-s-mode-in-windows-4f56d9be-99ec-6983-119f-031bfb28a307

**Comment by alex2364** [comment]
> > I would like to add my support for a Microsoft Store UWP app! I'm looking for a client that I can install in Windows S mode. I'm not too concerned with performance as long as it works. Something similar to the Cisco AnyConnect app in the Microsoft Store would be great.
> 
> I still don't understand why people still like to use the limited Windows on S mode. It is so limited that we can't run any batch file or task planner. I would suggest to deactivate the S mode to be able to use windows in a more efficient way (window S mode is a false feeling of security anyway): https://support.microsoft.com/en-us/windows/switching-out-of-s-mode-in-windows-4f56d9be-99ec-6983-119f-031bfb28a307

I still don't understand why people like to judge other people on how they use their computers when the real issue of this is the lack of UWP app in the Microsoft Store. Whether or not you use Windows S mode, everyone can benefit from a Microsoft Store UWP app. Thanks for not contributing to anything in this thread!

**Comment by gitnewcomer** [comment]
> > > I would like to add my support for a Microsoft Store UWP app! I'm looking for a client that I can install in Windows S mode. I'm not too concerned with performance as long as it works. Something similar to the Cisco AnyConnect app in the Microsoft Store would be great.
> > 
> > 
> > I still don't understand why people still like to use the limited Windows on S mode. It is so limited that we can't run any batch file or task planner. I would suggest to deactivate the S mode to be able to use windows in a more efficient way (window S mode is a false feeling of security anyway): https://support.microsoft.com/en-us/windows/switching-out-of-s-mode-in-windows-4f56d9be-99ec-6983-119f-031bfb28a307
> 
> I still don't understand why people like to judge other people on how they use their computers when the real issue of this is the lack of UWP app in the Microsoft Store. Whether or not you use Windows S mode, everyone can benefit from a Microsoft Store UWP app. Thanks for not contributing to anything in this thread!

If you knew the limitations of Windows on S mode and the possibility of OpenVPN, you should know that both are not compatible. An example: Windows on S mode does not allow the use of scripts, how do you implement the client side scripting of OpenVPN (https://openvpn.net/vpn-server-resources/explanation-of-client-side-scripting-with-simple-examples/) even if you would have a UWP app? It doesn't make sense developing something that will only partial work. If you need OpenVPN, then you need to disable the S mode of Windows to use it, this is why Microsoft allows it and also gives you steps to do it. Did you know what happened to Windows RT? The Windows version that only allowed apps from Microsoft Store and didn't have a way to disable it like on S mode in this days? Yeah, nobody wanted to develop for it because UWP apps are limited, so Microsoft abandoned the OS. You should be glad that there is a possibility to disable the S mode on Windows 10/11...

**Comment by cron2** [comment]
Hi,

could you please discuss the benefits (or not) of Win10 S mode outside
this issue?  It has nothing to do with OpenVPN GUI.

If someone wants to write an UWP app, and someone else finds that useful,
it's their choice.

*We* are currently not going to invest development time into the UWP
app, because we're massively short on resources - as in, we have more
urgent issues that need to be taken care of.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
