### ISSUE TITLE
Italian language file not updated from a long time

### ISSUE THREAD

**Issue by bovirus** [OpenVPN/openvpn-gui#533]
@selvanair 

From 11.07.2022 when I propose the some changes to update align the italian translation nothing changed.

The current italian translation now as in the past is not aligned to master english, contain English text, and for me use old terminology of an old style of translatioin.

I propose to the original translator (@odex) to update the translation and keep focus on it (check and update every time that there are some changes in english UI file).

If he don't have time for do this job I propose to leave the job to someone that have time for it and maintain it frequently .

Thanks.

**Comment by ordex** [comment]
FTR I am not the "original translator" - I am just a native Italian speaker and OpenVPN developer.
Code is open for contributions by everybody.

Cheers,

**Comment by bovirus** [comment]
@ordex 

Does it men that no one is in charge to translate and maintain updated the italian language for OpenVPN?

**Comment by ordex** [comment]
Hi! I am not sure what you mean with "in charge". This is an open source project, so everybody can be responsible and everybody can be in charge.

**Comment by bovirus** [comment]
If you are italian you can understande "l'asino di due padroni muore di fame e di sete".

If there are many owners that could manage a translation (ex. italian) and for exmpale anyone think that someone of the other will manage it, could happend like it seems now that italian translation is not updated, contains english terms and so on.

For a better efficiency In many project where I partecipated the language files are moved from github to place more orienetd to translation (like Crowdin or Transiflex) leaving on github only the csource code.

**Comment by dsommers** [comment]
@bovirus OpenVPN and this sub-project, OpenVPN-GUI, are fully open source projects.  They take contributions, contributions are reviewed, and when they look good they are merged.

Translations are not treated any different, also because there are lots of terminologies in the VPN scope which needs to be used correctly.  We've even seen attempts to translate product names of OpenVPN Inc, which then just gets comical.  And contributors not fully grasping the scope being translated are therefore begin reviewed far more careful, which can be felt like a resistance to accept the changes.

Using other services to handle translations is just about the tool itself, it doesn't change the fact that translations also needs to be reviewed carefully.  For this sub-project @selvanair has grown in the community to take the main lead (for which we are all truly happy for!).  Choice of tools to use is then entirely up to those being in the main lead of these various sub-projects; for OpenVPN GUI the final word here ends up with @selvanair's decision.  And AFAIK, he doesn't speak Italian, so he need to rely on the community to do the reviews.

Also, reviews are preferred to be reviewed by trusted community members.  @ordex is highly trusted within all the various OpenVPN projects.  You may also become a trusted community member as well.  But it takes efforts. You need to participate actively, contribute with changes, follow up, join our meetings, etc, etc - in other words let the community get to know you and your skills through what you do.  Open source projects builds on the principles around meritocracy. 

It's sad to say it, but the attitude you've taken in this "issue" is not helping you to build the needed community trust.  And also creating this as a GitHub Issue instead of a Discussion is also somewhat peculiar.

I will let it be up to @selvanair to decide how to handle this issue and translations in general.  But from my perspective, this "issue" can be closed.

**Comment by bovirus** [comment]
@dsommers

Sorry but I didn't understand your answer.

I partecipate at many different project and is the first time that I see this answer.

The current OpenVPN GUI italian translation for me that I'm a profesisonal translator that works for many sofwtare project  (search bovirus on internet)  is not complete because it's a mix of italian/english words, not laigned to amsetr english and use sometime not modern terms (genral informatic terms - not VPN terms).  

In other project if someone report in the project repository that translaction is incomplete and propose some changes highlighting which are the issues, the porpositive approcah is

Say thanks you for the time spent to do this task
Analyze and check if can be useful

Here from a long time of my last poost (4 months ago) I reported that italian language was not updated and contains (for me) some errros, and now after 4 months, where no one take a time to update the italian translation, I propose a new version updated, and I open an issue for it (becaise for me it's a project issue).

I believe that there many trusted member can update the italian translation.

I cannoty imagine how can consider close this issue (the translation now is not completed and then translation is part of the project).

If someone of your trusted member can complete the italian ytranslationall ialian user will be happy.

Thanks.

**Comment by bovirus** [comment]
@selvanair 

I believe that @ordex can open the file and make all changes that he likes and propose it as update.

To make it easily in short time we could do in this way.

1. merge my PR.
2. @ordex make his changes and prose it as your request and your merge it.

Thanks.

**Comment by bovirus** [comment]
Then I cannot see any other solution that a trusted member get my translation proposal, make his changes and propose it as trusted translation.
It's important that some trusted member do it to have finally an italian translation complete.

**Comment by schwabe** [comment]
@bovirus we generally do not like this hit & run approach with contributions. We often had people suggesting changes (program code) that post a patch and then never put the effort into it, to make into a acceptable state. And basically we ask all contribution to be a good shape. 

Yes, someone else can take off the work of you (or other contributers) and change the contribution into an an acceptable state but generally we expect the original submitter to put that work into their submission and not try offload that to others.

**Comment by schwabe** [comment]
And seeing that we asked not to translate "OpenVPN Access Server" and you said "fixed" to that and then opened a PR that still has the translation in it, feels like you did not put in any effort. I haven't checked the other suggestions that were made but I believe @selvanair when he says that they are also not made.

**Comment by bovirus** [comment]
@schwabe 

My approach is different.
I don't have knowledge about programming and for this I checked and proposed only translation changes.

It's my habit (for other projects where I followed the tranmslation) to check always befote and after program release (because for example the GUI size and text string lenght can checked only after release the new program version with GUI changes)

For me any solution that develòoper like it's ok.
My final scope is only to have a modern italian translation translated at 100%.

Any solution that can offer to get this result for me is OK.
