### ISSUE TITLE
Improving the Persian(Farsi) translation of the project

### ISSUE THREAD

**Issue by DanielBlackBeard** [OpenVPN/openvpn-gui#544]
Hi, I would like to cooperate with you in improving the Persian language of this project so that these users have a better user interface experience.

**Comment by lstipakov** [comment]
Sure, feel free to open a pull request with translations!

**Comment by DanielBlackBeard** [comment]
https://github.com/OpenVPN/openvpn-gui/pull/545

**Comment by DanielBlackBeard** [comment]
persian language is an RTL language.
RTL (Right To Left) is a locale property indicating that text is written from right to left. 
When written from left to right with specialized English words, the order of the words will be messed up.
It's an example of correcting its position of it. 
![image](https://user-images.githubusercontent.com/118456291/204101529-fc3aba1c-3050-4276-b3cc-82976ffa09d8.png)
*I don't know how to do it.

languages that are RTL : 
Persian language
Arabic script
Hebrew alphabet
*other middle east languages,...

**Comment by DanielBlackBeard** [comment]
I have a good idea for reordering positions of UI automatically. 
I found a great solution.

I took a screenshot of the translated UI and took it into Photoshop, and flipped images => rotate => Flip canvas horizontally.
The positioning of UI elements is solved.
In my idea, There is a need for a coefficient that needs to be flipped based on the horizontal. If I am not mistaken, the x-axis position should have a negative coefficient if the center is in the middle.
![image](https://user-images.githubusercontent.com/118456291/204142866-17d53ebc-e475-49e5-9a26-c2eebf2d8c31.png)

**Comment by selvanair** [comment]
RTL language display has to be handled in the resources (and by run-time style changes when required), not by flipping images in photoshop.  Mirroring is not same as writing right to left, nor is such image manipulation useful for implementing dialog windows.

Please test PR #546 that sets Farsi dialogs to display as RTL,  and provide feedback  -- you can test it using an executable from CI builds: https://github.com/OpenVPN/openvpn-gui/actions/runs/3560349296#artifacts)

I've left the status window unchanged as it requires special handling to have some widgets like buttons and title as RTL but the rich-text window (logs from the daemon) kept in LTR order (or so I feel). Please advise how a Farsi user would want to see it. For other windows, some tweaks in the text may be needed so that English-Farsi mixed sentences display correctly -- see the wrong formatting in About window for example.

**Comment by DanielBlackBeard** [comment]
> RTL language display has to be handled in the resources (and by run-time style changes when required), not by flipping images in photoshop. Mirroring is not same as writing right to left, nor is such image manipulation useful for implementing dialog windows.
> 
> Please test PR #546 that sets Farsi dialogs to display as RTL, and provide feedback -- you can test it using an executable from CI builds: https://github.com/OpenVPN/openvpn-gui/actions/runs/3560349296#artifacts)
> 
> I've left the status window unchanged as it requires special handling to have some widgets like buttons and title as RTL but the rich-text window (logs from the daemon) kept in LTR order (or so I feel). Please advise how a Farsi user would want to see it. For other windows, some tweaks in the text may be needed so that English-Farsi mixed sentences display correctly -- see the incorrect formatting in About window for example.

I will test it soon. Thanks for that.

**Comment by DanielBlackBeard** [comment]
> RTL language display has to be handled in the resources (and by run-time style changes when required), not by flipping images in photoshop. Mirroring is not same as writing right to left, nor is such image manipulation useful for implementing dialog windows.
> 
> Please test PR #546 that sets Farsi dialogs to display as RTL, and provide feedback -- you can test it using an executable from CI builds: https://github.com/OpenVPN/openvpn-gui/actions/runs/3560349296#artifacts)
> 
> I've left the status window unchanged as it requires special handling to have some widgets like buttons and title as RTL but the rich-text window (logs from the daemon) kept in LTR order (or so I feel). Please advise how a Farsi user would want to see it. For other windows, some tweaks in the text may be needed so that English-Farsi mixed sentences display correctly -- see the incorrect formatting in About window for example.

Tested on build ,openvpn-gui_x64_ossl1.1.1

Actually its Great . thanks for that .
The user interface is very clean and good, and it is prepared to add even Arabic and Hebrew languages.
The rest of the defects are very small. 

![image](https://user-images.githubusercontent.com/118456291/204337958-4a5c643e-2954-48ef-bd09-a754c014b56e.png)

![image](https://user-images.githubusercontent.com/118456291/204338612-0c58ed12-db15-448e-ad69-740c445da6aa.png)

![Untitled-2](https://user-images.githubusercontent.com/118456291/204346199-55012e1e-bc07-4e61-9682-ef0aefd095a4.png)

**Comment by selvanair** [comment]
Thanks for the feedback. The first one is an error popup window which are not convered by this PR -- will handle in a separate PR.

Truncated text are supposed to be fixed during translation by changing the geometry parameters to accommodate the translated text. 

For the last one, the wrong placement of trailing < and / are fixed in the second commit I pushed a few hours ago. Please retest "About" window using the latest CI binaries.

As for error in translation or missing spaces, please fix them in your PR 545  -- I do not speak or understand Farsi.  I'll merge this for now so that you can rebase #545 on top of this and test.

**Comment by selvanair** [comment]
@DanielBlackBeard PR #547 should fix alignment and order in the error messages that you pointed out. Does the image below look right?
![error-connecting](https://user-images.githubusercontent.com/3981391/204598631-9a32d747-ad81-425f-8e12-3b9d246ff9ec.png)
