### ISSUE TITLE
unconditional check for openssl in configure.ac

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-gui#56]
openvpn-gui might be compiled with "password change disable" defined. in such case we do not need openssl at all

maybe we should make that check conditional?

**Comment by selvanair** [comment]
You are right, currently to build without openssl we still have to define some dummy path for the crypto LIB and INCLUDE because of this check.  It would be nice to have a configure option like --disable-change-password or --with-openssl=yes/no and make this check conditional. Or even automatically disable change password if openssl not found.
