### ISSUE TITLE
Disable username/password dialog popup when remember password is set

### ISSUE THREAD

**Issue by JPTIZ** [OpenVPN/openvpn-gui#566]
Sometimes when using an slightly unstable connection, OpenVPN will disconnect and attempt to reconnect in 5s. But since everytime it disconnects it asks for the password, the "Enter username password" window keeps popping up and becomes quite annoying since there's no intention in changing either username nor password.

My suggestion would be to, when "Remember username/password" (something like it) is checked, do not show the popup for the same connection. If this is not always desired, then it could become a toggle in configurations.

**Comment by cron2** [comment]
Hi,

On Tue, Dec 20, 2022 at 04:19:45AM -0800, João Paulo Taylor Ienczak Zanette wrote:
> Sometimes when using an slightly unstable connection, OpenVPN will disconnect and attempt to reconnect in 5s. But since everytime it disconnects it asks for the password, the "Enter username password" window keeps popping up and becomes quite annoying since there's no intention in changing either username nor password.
> 
> My suggestion would be to, when "Remember username/password" (something like it) is checked, do not show the popup for the same connection. If this is not always desired, then it could become a toggle in configurations.

You have something in your openvpn config which makes openvpn ask
the GUI for password again - most likely "auth-nocache".  Getting rid
of that would be the easiest way to get rid of repetitive prompts...

@selva: can we see if the core is asking because of AUTH_FAILED or because
of auth-nocache?  In the "we just reconnect and auth-nocache is in effect",
the GUI could indeed try to resend previously saved credentials, without
asking.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
Though the GUI pops up the password dialog, if password is saved and there is no AUTH_FAIL, it does submit the dialog with a 5 second delay. This is done so that a user can change username (and password), if desired (even if the saved pair is correct). If we completely hide the dialog, user will have to clear the saved password to see the dialog again.  Saved private key password is always submitted without a popup (unless it fails to verify) as there the only reason for the user to edit it is when the password is wrong. 

I have never felt it as a nuisance, and works unattended. Unless this popup happens too frequently in which case the issue is elsewhere as explained above.

**Comment by cron2** [comment]
Hi,

On Tue, Dec 20, 2022 at 08:24:10AM -0800, Selva Nair wrote:
> Though the GUI pops up the password dialog, if password is saved and there is no AUTH_FAIL, it does submit the dialog with a 5 second delay. 

Ah.  I was not aware that the GUI already does this.

For me, this is a good approach.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by sk8rthug** [comment]
Well, the problem still exists and this pop-up pisses me off. It apperars on every micro disconnect that happens every 30 min or so in my case. I would like to have an option the author has described.

**Comment by selvanair** [comment]
> Well, this pop-up pisses me off. It apperars every 30 min or so in my case. I would like to have an option the author has described too.

Look for  `auth-nocache` in the client configuration file and remove it.  Alternative is to set `silent-connection` in  the GUI settings.

**Comment by sk8rthug** [comment]
> Look for `auth-nocache` in the client configuration file and remove it.

it worked, thanks!
