### ISSUE TITLE
> Greate Fie for stdout 系统找不到指定的文件

### ISSUE THREAD

**Issue by RowinaDu** [OpenVPN/openvpn-gui#673]
求助求助

当我打开vpn时报这个错，试了好多个版本都是一样的问题。 电脑的版本是win10专业版。

<img width="424" alt="error" src="https://github.com/OpenVPN/openvpn-gui/assets/27999123/bc28d8d1-c01e-417c-9c92-6906cb71703a">

**Comment by selvanair** [comment]
> 当我打开vpn时报这个错，试了好多个版本都是一样的问题。 电脑的版本是win10专业版

Report issues in English please --- google translate will help :)

Anyway, it seems your system fails opening 'NUL' which is used by the service to redirect stdout. Try the following from a command prompt:

`echo something > NUL`

If that gives the same error, your Windows system is misconfigured.

In case you had deliberately disabled the NUL "device", turn it back on. Otherwise this could be sign of badly broken system and not something we could properly help with.
